from typing import Dict

TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "en": {
        "welcome": "Welcome {name}!\n\nAtom Media Bot helps you search movies and series, save favorites, request missing content, report problems, and unlock protected videos after watching ads.",
        "search_prompt": "Enter movie or series name:",
        "no_results": "This movie or series is not available yet. You can request it and admins will review it.",
        "search_results": "Search results:",
        "searching": "Searching movies and series...",
        "movie_not_found": "Movie not found.",
        "series_not_found": "Series not found.",
        "request_prompt": "Send the movie/series name or a poster image.",
        "request_sent": "Your request has been sent to the admin team. Thank you!",
        "report_prompt": "Report",
        "report_desc_prompt": "Please describe the problem briefly.",
        "report_thanks": "Thank you for your report. Admins will review it.",
        "rep_broken_video": "Broken Video",
        "rep_wrong_subtitle": "Wrong Subtitle",
        "rep_wrong_episode": "Wrong Episode",
        "rep_quality_problem": "Quality Problem",
        "rep_other": "Other",
        "choose_language": "Please choose your language.",
        "language_saved": "Language saved.",
        "help_text": "I can help you find movies and series, save favorites, request missing titles, or report playback problems. Choose a button below, or type a movie name and I will search for it.",
        "assistant_fallback": "I am here to help. If you are looking for a movie or series, tap Search or send the title. If it is missing, tap Request Movie. If something does not play correctly, tap Report.",
        "unknown_answer": "I do not have a clear answer for that yet. You can request the movie here or contact the admin directly.",
        "btn_contact_admin": "Contact admin",
        "btn_search": "🔍 Search",
        "btn_favorites": "⭐ Favorites",
        "btn_request": "🎥 Request Movie",
        "btn_request_this": "🎥 Request this",
        "btn_report": "📝 Report",
        "btn_language": "🌐 Language",
        "btn_add_fav": "Add to Favorites ❤️",
        "favorites_empty": "No favorites yet. Add movies or series from search results.",
        "episode_not_found": "Episode not found.",
        "episode": "Episode",
        "fav_added": "Added to favorites.",
        "fav_removed": "Removed from favorites.",
        "fav_list_title": "Your favorites:",
        "fav_movie_label": "Movie:",
        "fav_series_label": "Series:",
        "ads_disabled_msg": "Ads are disabled for your account. Your protected video has been sent.",
        "watch_prompt": "Please watch the advertisement to unlock this video.",
        "no_active_polls": "No active polls.",
        "poll_question": "📊",
        "poll_closed": "Poll closed.",
        "already_voted": "You already voted.",
        "vote_recorded": "Vote recorded!",
    },
    "mm": {
        "welcome": "{name} မင်္ဂလာပါ။\n\nAtom Media Bot မှာ ရုပ်ရှင်နဲ့ ဇာတ်လမ်းတွဲတွေကို ရှာဖွေနိုင်ပါတယ်။ ကြိုက်နှစ်သက်မှုစာရင်းသိမ်းနိုင်ပြီး မရှိသေးတဲ့ရုပ်ရှင်တွေကို တောင်းခံနိုင်ပါတယ်။ ကြည့်မရတာ၊ အပိုင်းမှားတာ၊ Quality ပြဿနာတွေကိုလည်း Report ပို့နိုင်ပါတယ်။",
        "search_prompt": "ရုပ်ရှင် (သို့) ဇာတ်လမ်းတွဲအမည် ရိုက်ထည့်ပါ:",
        "no_results": "ဒီရုပ်ရှင် (သို့) ဇာတ်လမ်းတွဲကို မရှိသေးပါ။ တောင်းခံပေးပို့နိုင်ပါတယ်၊ Admin မှ စစ်ဆေးပြီး ထည့်ပေးပါမယ်။",
        "search_results": "ရှာဖွေမှုရလဒ်များ:",
        "searching": "ရုပ်ရှင်နှင့် ဇာတ်လမ်းတွဲများ ရှာဖွေနေပါသည်...",
        "movie_not_found": "ရုပ်ရှင်ကို မတွေ့ပါ။",
        "series_not_found": "ဇာတ်လမ်းတွဲကို မတွေ့ပါ။",
        "request_prompt": "ရုပ်ရှင်နာမည် (သို့) Poster ပေးပို့ပါ။",
        "request_sent": "တောင်းခံမှုကို Admin ဆီ ပေးပို့ပြီးပါပြီ။ ကျေးဇူးတင်ပါတယ်။",
        "report_prompt": "Report",
        "report_desc_prompt": "ပြဿနာအကြောင်း အသေးစိတ်ရေးပေးပါ။",
        "report_thanks": "Report ပေးပို့ပြီးပါပြီ။ Admin မှ စစ်ဆေးပေးပါမယ်။",
        "rep_broken_video": "ဗီဒီယိုမရပါ",
        "rep_wrong_subtitle": "စာတန်းမှားနေသည်",
        "rep_wrong_episode": "အပိုင်းမှားနေသည်",
        "rep_quality_problem": "အရည်အသွေးပြဿနာ",
        "rep_other": "အခြားပြဿနာ",
        "choose_language": "ဘာသာစကား ရွေးချယ်ပါ။",
        "language_saved": "ဘာသာစကား သိမ်းပြီးပါပြီ။",
        "help_text": "ရုပ်ရှင်/ဇာတ်လမ်းတွဲ ရှာဖို့၊ ကြိုက်နှစ်သက်မှုသိမ်းဖို့၊ မရှိသေးတဲ့ကားတောင်းဖို့၊ ကြည့်မရတဲ့ပြဿနာ Report ပို့ဖို့ ကူညီပေးနိုင်ပါတယ်။ အောက်ကခလုတ်ကိုရွေးပါ၊ ဒါမှမဟုတ် ရုပ်ရှင်နာမည်ကို တိုက်ရိုက်ရေးပို့ပါ။",
        "assistant_fallback": "ကူညီပေးဖို့ အသင့်ရှိပါတယ်။ ရုပ်ရှင်/ဇာတ်လမ်းတွဲရှာချင်ရင် Search ကိုနှိပ်ပါ သို့မဟုတ် နာမည်ရေးပို့ပါ။ မရှိသေးရင် ရုပ်ရှင်တောင်းခံကိုနှိပ်ပါ။ ကြည့်မရတာရှိရင် Report ပို့နိုင်ပါတယ်။",
        "unknown_answer": "ဒီမေးခွန်းအတွက် တိတိကျကျမရှိသေးပါ။ ဒီကားကိုတောင်းခံနိုင်သလို Admin ကိုလည်း တိုက်ရိုက်ဆက်သွယ်နိုင်ပါတယ်။",
        "btn_contact_admin": "Admin ကိုဆက်သွယ်ရန်",
        "btn_search": "🔍 ရှာဖွေရန်",
        "btn_favorites": "⭐ ကြိုက်နှစ်သက်မှု",
        "btn_request": "🎥 ရုပ်ရှင်တောင်းခံ",
        "btn_request_this": "🎥 ဒီကားကို တောင်းခံမယ်",
        "btn_report": "📝 Report",
        "btn_language": "🌐 ဘာသာစကား",
        "btn_add_fav": "ကြိုက်နှစ်သက်မှုထဲ ထည့်ရန် ❤️",
        "favorites_empty": "ကြိုက်နှစ်သက်မှုစာရင်း မရှိသေးပါ။ ရှာဖွေမှုရလဒ်ထဲကနေ ထည့်နိုင်ပါတယ်။",
        "fav_added": "ကြိုက်နှစ်သက်မှုထဲ ထည့်ပြီးပါပြီ။",
        "fav_removed": "ကြိုက်နှစ်သက်မှုထဲမှ ဖယ်ရှားပြီးပါပြီ။",
        "fav_list_title": "သင့်ကြိုက်နှစ်သက်မှုစာရင်း:",
        "fav_movie_label": "ရုပ်ရှင်:",
        "fav_series_label": "ဇာတ်လမ်းတွဲ:",
        "episode": "အပိုင်း",
        "ads_disabled_msg": "သင့်အကောင့်အတွက် ကြော်ငြာပိတ်ထားပါတယ်။ ဗီဒီယိုကို တိုက်ရိုက်ပို့ပေးပြီးပါပြီ။",
        "watch_prompt": "ဗီဒီယိုဖွင့်ရန် ကြော်ငြာကို အရင်ကြည့်ပေးပါ။",
    }
}


def get_text(lang: str, key: str, **kwargs) -> str:
    """Get translated text for a given language and key."""
    translations = TRANSLATIONS.get(lang, TRANSLATIONS["en"])
    text = translations.get(key, TRANSLATIONS["en"].get(key, key))
    return text.format(**kwargs) if kwargs else text
